[package]
name = "stakedex_withdraw_stake_interface"
version = "0.1.0"
edition = "2021"

[dependencies.borsh]
workspace = true

[dependencies.solana-program]
workspace = true

[dependencies.serde]
optional = true
workspace = true
